#!/bin/bash
##
# Author: Benno K.
# Email: benno@xyz.de
# Github: https://www.github.com/Benno-K
# 
# This script is available for
# public use under GPL V3 (see
# file LICENSE)
##

if [ "$1" = "-c" ]; then
	cdel="$2"
	shift # -c
	shift # delimiter
else
	cdel="#"
fi
grep -Ev "^${cdel}|^$" $@
