#!/bin/bash
##
# Author: HimbeerToni
# Email: Toni.Himbeer@fn.de
# Repos: https://codeberg.org/Himbeertoni/PublicScripts
# 
# This script is available for
# public use under GPL V3 (see
# file LICENSE)
##

if [ "$1" = "-c" ]; then
	cdel="$2"
	shift # -c
	shift # delimiter
else
	cdel="#"
fi
grep -Ev "^${cdel}|^$" $@
