#!/bin/bash

##
# Author: Benno K.
# Email: benno@xyz.de
# Github: https://www.github.com/Benno-K
# 
# This script is available for
# public use under GPL V3 (see
# file LICENSE)
##

# Easily edit or list files in
# /etc/cron.d which usually
# come with some software that
# needs to run frequently, 
# e. g. can be used for the 
# diskusage script.

crond=/etc/cron.d

if [ "$1" = "-l" ]; then
  ls $crond
	exit
fi
if [ "$1" = "-d" ]; then
	rm -i $crond/$2
	exit
fi
if [ "$1" = "-c" ]; then
	cat <<<$(ctab) > $crond/$2
	exit
fi

vi $crond/$1
fi

exit
