#!/bin/bash

##
# Author: Benno K.
# Email: benno@xyz.de
# Github: https://www.github.com/Benno-K
# 
# This script is available for
# public use under GPL V3 (see
# file LICENSE)
##

# Easily edit or list files in
# /etc/cron.d which usually
# come with some software that
# needs to run frequently, 
# e. g. can be used for the 
# diskusage script.

[ $UID != 0 ] && exec sudo $0 $@ # run as root

crond=/etc/cron.d

if [ "$1" = "-l" ]; then
  ls $crond
	exit
fi
if [ "$1" = "-s" ]; then
	cat $crond/$2
	exit
fi
if [ "$1" = "-d" ]; then
	rm -i $crond/$2
	exit
fi
if [ "$1" = "-c" ]; then
	ofn=$2
	shift # -c
	shift # filename
	cat <<<$(ctab "$@") > $crond/$ofn
	exit
fi

vi $crond/$1

exit
