#!/bin/bash

# Script to create s line
# for a cron tab
# Parameters:
#  Time of day (eg. 14:30, 
#  but also possible *:0
#  *:* 0:* and everything else
#  that can go into the first
#  two fields of a crontab
#  (see "man 5 crontab")
#  Take care if you specify
#  a time without a colon (:)
#  as the order of parameters
#  is still hour followed by
#  minute (in contrary to the
#  order of crontab which is
#  minute followed by hour):

##
# Author: Benno K.
# Email: benno@xyz.de
# Github: https://www.github.com/Benno-K
# 
# This script is available for
# public use under GPL V3 (see
# file LICENSE)
##

if [ "$1" == "-s" ]; then
	silent="test -x"
	shift
fi

echo $1|grep -q :
if [ $? == 0 ]; then
	h=${1:0:2}
	m=${1:3:2}
	if [ "${1:2:1}" != ":" ] ||
		 [ "${1:5:1}" != "" ]; then
	  echo >&2 "Illegal time format: $1"
		exit 2
	fi
	if [ $m -gt 59 ] ||
	   [ $h -gt 23 ]; then
	  echo >&2 "Illegal time: $1"
		exit 2
	fi
fi
if [ "$h" == "" ]; then
 if [ "$1" == "" ]; then
  echo -n >&2 "hour (0-23): "
  read n
 else
	h=$1
	shift
 fi
 if [ "$1" == "" ]; then
  echo -n >&2 "minute (0-59):"
  read m
 else
	m=$1
	shift
 fi
else
	h=${1:0:2}
	m=${1:3:2}
	shift
fi

choice="$1"
shift
while [ "$choice" == "" ] && [ "$choice" != "m" ] && [ "$choice" != "w" ]
do	
	echo -n >&2 "run monthly or weekly (m/w): "
	read choice
done

if [ "$choice" == "w" ]; then
	wd="$1"
	# Numeric? Then check range
	if [[ $wd =~ '^[0-9]+$' ]] &&
	   ([ $wd -gt 7 ] ||
		  [ $wd -lt 0 ]); then
	  echo >&2 "Illegal weekday: $1"
		exit 2
	fi
	shift
	if [ "$wd" == "" ]; then
    echo -n >&2 "day of week (0-7, 0=7=Sun): "
    read wd
	else
    md='*'
	fi
	my="*"
else
	md="$1"
	# Numeric? Then check range
	if [[ $md =~ '^[0-9]+$' ]] &&
	   ([ $md -gt 31 ] ||
		  [ $md -lt 1 ]); then
	  echo >&2 "Illegal day of month: $1"
		exit 2
	fi
	if [ "$md" == "" ]; then
	  echo -n >&2 "day of month (0-31): "
	  read md
	else
	  shift
	fi
	my=$1
	# Numeric? Then check range
	if [[ $my =~ '^[0-9]+$' ]] &&
	   ([ $my -gt 12 ] ||
		  [ $my -lt 1 ]); then
	  echo >&2 "Illegal month: $1"
		exit 2
	fi
	if [ "$my" == "" ]; then
	  echo -n >&2 "month (1-12): "
	  read my
	else
	  shift
	fi
	wd='*'
fi
u="$1"
shift
if [ "$u" == "" ]; then
 echo -n >&2 "run as (username, default= $USER): "
  read u
	if [ "$u" == "" ]; then
		u=$USER
	fi
fi

cmd="$@"
while [ "$cmd" == "" ]
do
  echo -n >&2 "command: "
  read cmd
done

echo "$m $h	$wd $md	$my	$u	$cmd"
exit
