#!/bin/bash

# Enter DynDNS name for FritzBOX
#  * to obtain a new certificate with getssl 
#	   it must point to server2's IPv6
#  * for normmal remote reachabilty the name
#    must point to the FritzBOX's IPv6
#  as you must specify IPv4 as well fori
#  Strato's DDNS service we do this as well
#
# This script depends on extip, extip6 and
# ifip6 which return the addresses of server
# and FritzBOX

# get what to send from commandline
case $1 in
	-to-server|-s|s)
		ipv6=$(ifip6)
		;;
	-to-fritzbox|-f|f)
		ipv6=$(extip6)
		;;
	"")
		echo "usage: $0 -to-server|-to-fritzbox" >&2
		exit 1

		;;
esac

# Define top-level domain, sub domain and
# something else for URL
tld="kardel.eu"
sub="fbx"
trg=${sub}.${tld}
sth="stratogisches123KW"

# build URL
url="${tld}:${sth}@dyndns.strato.com/nic/update?hostname=${trg}&myip=$(extip),${ipv6}"
# and go
curl -s ${url}
exit
