#!/bin/bash
#
# Wrapper around Dovecot LDA
#  decides Inbox or Junk (if spam)
#  Decision/Action by a "rule" file
#  containing a Regex (MUST not include
#  space characters - unless specified
#  as [[:space:]]) followed by a space
#  character followed by whatever should
#  be added to the final lda command
#  Example:
#   ^X-Spam-Status:[[:space:]]*Y[eE][sS] -m Junk
#   which adds "-m Junk" to the lda
#   command to deliver to correct mailbox
#  Theoretically any mail-content can be used
#  to deliver to a specific folder
#   
# Pros:
#  No reinjection
#  No Postfix filters
#  No sieve
# Con:
#  Needs to temporary duplicate the mail
#
##
# Author: Benno K.
# Email: benno@xyz.de
# Github: https://www.github.com/Benno-K
# 
# This script is available for
# public use under GPL V3 (see
# file LICENSE)
##

set -euo pipefail
# -e : exit immediately on error
# -u : treat unset variables as an error
# -o pipefail : fail if any command in a pipeline fails

# Local delivery agent to invoke
lda=/usr/lib/dovecot/dovecot-lda
# Regex/Mbox pairs
reFil=/etc/dovecot/mboxrules
# parameters: sender and recipient (from 
# postfix transport)

# POSIXy $(basename $0)
me=${0##*/}

if [ ! -e "$reFil" ]; then
	msg="missing rule file $reFil"
	logger -p mail.info "$(date +%Y-%m-%dT%H:%M:%S.%6N%:z) $me: $msg"
	echo >&2 $msg
	exit 1
fi
# Tempfile to hold mail 
#  is grepped for each regexp in $reFil and
#  finally passed on to the lda 
tmp="$(mktemp /tmp/${me}.XXXXXX)" || exit 75
cleanup() {
  [ -e "$tmp" ] && rm -f "$tmp"
}
trap cleanup EXIT HUP INT TERM

#
# Preserve full message
cat > "$tmp"

# Read the definitions from file
opts=
lc=0
while IFS= read -r reLine; 
	do
	regexp=${reLine%% *}
	suffix=${reLine#* }
	lc=$((lc++))
	if grep -Eq "$regexp" "$tmp"; then
		opts+="$suffix "
	else
		if [ $? = 2 ]; then
			logger -p mail.info "$(date +%Y-%m-%dT%H:%M:%S.%6N%:z) $me: error in regexp \"$regexp\" - line $lc in $reFil"
		fi
	fi

	done < "$reFil"
[ ! -z "$opts" ] && logger -p mail.info "$(date +%Y-%m-%dT%H:%M:%S.%6N%:z) $me: added \"${opts%* }\" to lda-command"

# logger -p mail.info "$(date +%Y-%m-%dT%H:%M:%S.%6N%:z) $me: calling $lda $opts $@"

# Do not exec as this would leave the $tmp file
$lda $opts $@ <"$tmp"
exit
