#!/bin/bash

# List detailed status for each fail2ban jail
if [ $UID = 0 ]; then
	sudo=
else
	sudo="sudo "
fi

for jail in $(${sudo}fail2ban-client status|awk '/Jail list:/{print substr($0,15)}'|sed -e s/,//g)
do
	${sudo}fail2ban-client status $jail
done
