#!/bin/bash

#Abstract:
# This script fetches the comic-strip of a
# certain kind from gocomics.com for a
# certain date.
# The default kind is nonsequitur.
# The default date is today.
# It replaces the nonsequitur-script which
# ceased to work with the latest 
# restructuring in 2025 of the GoComics 
# CMS-generated website
#
##
# Author: Benno K.
# Email: benno@xyz.de
# Github: https://www.github.com/Benno-K
# 
# This script is available for
# public use under GPL V3 (see
# file LICENSE)
##

loadConfigYml() {
    local yamlFile="$1"

    declare -gA para

    while IFS=$'\t' read -r key value; do
        para["$key"]="$value"
    done < <(
        yq e -o=tsv '
          to_entries
          | .[]
          | select(.value | type == "!!map")
          | .key as $section
          | .value
          | to_entries
          | .[]
          | [$section + "." + .key, (.value | tostring)]
        ' "$yamlFile"
    )
}

loadComicsYml() {
    local yamlFile="$1"

    # Read all comics in one yq call (TSV: key <tab> title <tab> by)
    while IFS=$'\t' read -r key comicTitle comicBy; do
        title["$key"]="$comicTitle"
        by["$key"]="$comicBy"
    done < <(
        yq e -o=tsv '
            . as $root
            | keys[]
            | . as $key
            | [$key, $root[$key].title // "", $root[$key].by // ""]
        ' "$yamlFile"
    )
}

# Variables for comic name and date
comic=${1:-nonsequitur}	# default comic
today=$(date +%Y/%m/%d)	# todays date
fetchDate=${2:-$today}	# default date
declare -A title
declare -A by
declare -A para

# Destination dir, based on comic and year
dstDir=~/${comic}/${fetchDate:0:4}

# Read from config
# Mail recipients - all empty = NO mail is sent
#
# Source the function used to mail image
. ${0%/*}/sendInlImgMai

comicCfg=~/.config/getGoComicsList.yml
paramCfg=~/.config/getGoComicsParams.yml

# Example config YAML (no tab chars!):
#mail:
#  to: root
#  cc: pi@example.com
#  bcc: John.Doe@nowhere.org
#  from: pi
#   if from: starts with an @, the from value
#   will be prefixed by the value of $comic.
loadConfigYml "${paramCfg}";

# the comic "database"
loadComicsYml "${comicCfg}"

if [ -z "${title[$comic]}" ]; then
	echo >&2 "Sorry, $comic not found in ${comicCfg}"
	exit 3
fi

# Replace spaces with dashes for file /prefix
prefix=$(echo "${title[$comic]}" | tr  ' ' '-')
outFil="${prefix}-${fetchDate//\//-}"
mailFrom="\"${comic}\" <${comic}@${mailFromDomain}>"

# API-Key needed for browserless.io - as ext apk is used
# There is a generic file  and an 
# app-specific file where it can be stored
# prefer the least.
apsdefault=~/.browserless.io.aps
apsspecific=~/.${0##*/}.aps

if [ -r  ${apsspecific} ]; then
	apsfil=${apsspecific}
else
	apsfil=${apsdefault}
fi
# Read the API-key when file exists,
# otherwise declare the necessity and cry
if [ -r ${apsfil} ]; then
        read apiKey < $apsfil
else
	cat <<-EOI
	You need an API-key from browserless.io
	for this script to work.
	Get one for free from https://browserless.io
	and store it as the only single line
	in $apsspecific or
	in $apsdefault
	and run ${0##*/} again
	EOI
	exit 1
fi

# build target url on GoComics
url="https://www.gocomics.com/${comic}/${fetchDate}"

# As retrieving the URL is time-consuming
# and counts for the amount of requests
# per browserless.io API key, we store
# the URL of the image for later use. This
# significantly speeds up repeated attempts!
urlStore="${dstDir}/.urlstore"
if [ ! -d "${urlStore}" ]; then
	mkdir -p "${urlStore}"
fi
storeFil="$urlStore/${fetchDate//\//-}"

if [ -r "${storeFil}" ]; then
	# use stored URL if it exists
	# this saves time and API-invocations
	read imgUrl <"${storeFil}"
else
	# Due to their s... CMS we need to scrape the
	# page using browserless.io to get HTML
	# - otherwise you only get tons of JavaScript
	# not containing the image's url
	imgUrl=$(
	curl -s -X POST \
		-H "Content-Type: application/json" \
		-H 'Cache-Control: no-cache' \
		-d "{\"url\": \"$url\"}" \
		"https://chrome.browserless.io/content?token=$apiKey" |
		perl -ne '
			# Date that GoComics actually serves
			if (!defined $serv &&
					/<link rel="canonical" href="https:\/\/www\.gocomics\.com\/[^\/]+\/(\d{4}\/\d{2}\/\d{2})"/) {
				$serv = $1;
			}
			# Image URL
			if (/<meta property="og:image" content="([^"]+)"/) {
				$img = $1;
			}
			# Tell bash either URL or mismatched date
			END {
				if (defined $serv && $serv ne "'$fetchDate'") {
					print "date:$serv\n";
				} else {
					print "$img\n" if defined $img;
				}
			}
		')
fi

# Nothing got, cannot continue
if [ -z "${imgUrl}" ]; then
	echo >&2 "cannot retrieve image file url"
	echo >&2 " from ${url}"
	echo >&2 " via https://chrome.browserless.io/content"
	exit 1
else
	# Check requested against received date
	# and give up on mismatch
	if [[ "${imgUrl:0:5}" == "date:" ]]; then
		echo >&2 "Date mismatch"
		echo >&2 " requested ${fetchDate}"
		echo >&2 " delivered ${imgUrl:5}"
		exit 2
	fi
fi

# Is there already a cartoon for this day?
#   Note: Make sure to have wildcard outside
#         the quotes!
outSpec=$(compgen -G "${dstDir}/${outFil}".???)
if [ ! -z "${outSpec}" ]; then
	# Exit silently in batch if file exists
	# but inform an interactive user
	tty -s && echo >&2 "already downloaded ${outSpec}"
else
	# Create temporary file to download image 
	tmpOut=$(mktemp "${HOME}/.${0##*/}-XXXXXXXD.tmp")
	# Make sure it is removed on exit
	trap "rm -f ${tmpOut}" EXIT

	# Get content-type of downloaded file while
	# downloading it
	cType=$(curl -s -w "%{content_type}" -o "${tmpOut}" "${imgUrl}")

	# Parts of content-type needed to determine extension
	major=${cType%/*}
	minor=${cType#*/}

	case "$major" in
		image)
			case "$minor" in
					jpeg) ext="jpg" ;;
					*)    ext=${minor}  ;;
			esac
			;;
		text) 			ext=${minor} ;;
		*) 					ext="bin" ;;
	esac

	# Move the file to it's destination
	case ${ext} in
		gif)
			# Special: convert GIF to PNG
			#  gif will be deleted on exit by trap
			outSpec="${dstDir}/${outFil}.png"
			convert "${tmpOut}" "${outSpec}"
			touch -d ${fetchDate//\//-} "${outSpec}"
			;;
			# Standard: move it as it is
			# and stop trap as there is
			# nothing left to delete
		jpg|png)
			# These can just be moved to destination
			# and trap for file deletion is cancelled
			outSpec="${dstDir}/${outFil}.${ext}"
			mv "${tmpOut}" "${outSpec}"
			trap - EXIT
			# Set the creation date accordingly
			touch -d ${fetchDate//\//-} "${outSpec}"
			;;
		*)
			# We received something unexpected
			echo >&2 "invalid content: ${cType}"
			echo >&2 " for ${imgUrl}"
			exit 1
	esac
fi

# If "from" starts with @, do prefix it with $comic
mailFrom="\"${title[$comic]}\" <${para[mail.from]/#@/${comic}@}>"

# Send mail if at least one recipient is given
if [ ! -z "${para[mail.to]}${para[mail.cc]}${para[mail.bcc]}" ]; then
	sendInlImgMai \
		-f "${mailFrom}" \
		-s "${title[$comic]}" \
		-c "${fetchDate:8:2}.${fetchDate:5:2}.${fetchDate:0:4}" \
		-hl "${title[$comic]}" \
		-bl '©&nbsp;'"${by[$comic]}"'&nbsp;'${fetchDate:0:4}'&nbsp;  https://gocomics.com/'${comic} \
		"${outSpec}" "${para[mail.to]}" "${para[mail.cc]}" "${para[mail.bcc]}"
fi
exit # (deleting temporary file due to trap)
