#!/bin/bash

parmDir=~/.config

getParms () {
	# For usage notes of status messages we
	# may need a basename ($me). It is set
	# to the function name when sourced but
	# set to the script name when executed
	[ "${BASH_SOURCE}" == "${0}" ] && me=${0##*/} || me=${FUNCNAME}
	parmFil="${parmDir}/${1}rc"
  if [ -r "${parmFil}" ]; then
    while IFS='=' read -r key value; do
      case "$key" in
        "mailFrom") mailFrom="$value" ;;
        "mailTo") mailTo="$value" ;;
				"mailCC") mailCC="$value" ;;
				"mailBCC") mailBCC="$value" ;;
      esac
    done < "${parmFil}"
	fi
}

[ "${BASH_SOURCE}" == "${0}" ] && ${0##*/} "$@"
