#!/bin/bash

# Script to clean uo
# KeePass database file
# Deletes all old filrs
# except one per month
# (one per month is kept)
# Keeps 2 months of 
# completely all days
# by default (= -k 2)

##
# Author: Benno K.
# Email: benno@xyz.de
# Github: https://www.github.com/Benno-K
# 
# This script is available for
# public use under GPL V3 (see
# file LICENSE)
##

function usage() {
  cat <<EOI
Usage: $0 [option [value]...
 Options:
  -name         name of database file,
                if it is "mypwds.kdbx", use "mypwds"
  -k num        number of months to keep the databases
  -dry          dryrun, don't remove files
  -begin year   go back to this year when scanning
  -makefake     will create a lot of faked databases
  -fakedays     specifies the days which wiil be created
	        per month
                specify as comma-separated list
                default is 7,17,27
  -store        store the values of -name, -dir, -k, -begin
                stored values will be taken as defaults on next invocation
  -v            verbose, list all files skipped and removed
  -h            help (this text)
EOI
}

dryrun=""
verbose=0
argc=0
args=""
fakedays=7,17,27
begin=2021
store=0
kdbxdir=KeePass
settings=~/.$(basename $0).settings
action=clean

if [ -r $settings ]; then
	 . $settings
fi

while [ "${1:0:1}" == "-" ]
do
	if [ "$1" == "-begin" ]; then
		shift
		begin=$1
		shift
		continue
	fi
	if [ "$1" == "-h" ]; then
		usage
		exit 0
	fi
	if [ "$1" == "-dry" ]; then
		dryrun=echo
		shift
		continue
	fi
	if [ "$1" == "-v" ]; then
		verbose=1
		shift
		continue
	fi
	if [ "$1" == "-makefake" ]; then
		action=mf
		shift
		continue
	fi
	if [ "$1" == "-fakedays" ]; then
		shift
		fakedays=$1
		shift
		continue
	fi
	if [ "$1" == "-dir" ]; then
		shift
		kdbxdir=$1
		shift
		continue
	fi
	if [ "$1" == "-name" ]; then
		shift
		kdbxname=$1
		shift
		continue
	fi
	if [ "$1" == "-store" ]; then
		shift
		store=1
		continue
	fi
	if [ "$1" == "-k" ]; then
		shift
		if [ "$1" == "" ]; then
			keep=6
		else
			keep=$1
		fi
	  shift
		continue
	else
   	echo >&2 "invalid option: $1"
		exit 1
  fi
done
if [ $store == 1 ]; then
  cat <<EOI > $settings
begin=$begin
kdbxname=$kdbxname
kdbxdir=$kdbxdir
keep=$keep
EOI
  exit
fi

while [ "$1" != "" ]
do
	args="$args$1 "
	shift
	((arg++))
done

if [ "$action" == "mf" ];then
	y=$(date +%Y)
	m=$(date +%m|sed -e s/^0//g)
	fakefor=$(echo $fakedays|sed -e s/,/\ /g)
	while [ $y -ge $begin ]
	do
	ms=$(printf "%02d" $m)
	for fd in $fakefor
	do
	  fd=$(printf "%02d" $fd)
		if [ $verbose == 1 ]; then
		  echo "creating $kdbxdir/$kdbxname.kdbx.$y-$ms-$fd-11-11-11"
		fi
		$dryrun touch "$kdbxdir/$kdbxname.kdbx.$y-$ms-$fd-11-11-11"
	done
	((m--))
	if [ $m = 0 ]; then
		m=12
		((y--))
	fi
  done
fi
if [ "$action" == "clean" ];then
	skc=0
	rmc=0
	y=$(date +%Y)
	m=$(date +%m|sed -e s/^0//g)
	fakefor=$(echo $fakedays|sed -e s/,/\ /g)
	skmonths=0
	while [ $y -ge $begin ]
	do
	ms=$(printf "%02d" $m)
	searchfor=$(ls -r $kdbxdir/$kdbxname.kdbx.$y-$ms-* 2>/dev/null)
	skipped=0
	for fn in $searchfor
	do
		fy=$(echo $fn | cut -d. -f3|cut -d- -f1)
		fm=$(echo $fn | cut -d. -f3|cut -d- -f2)
		if [ $skipped == 0 ]; then
			if [ $verbose == 1 ]; then
				echo skipped $fn
			fi
			((skipped++))
			((skc++))
			continue
		fi
	  if [ $skmonths -gt $keep ]; then
			if [ $verbose == 1 ]; then
		    echo remove $fm.$fy $fn
			fi
		  $dryrun rm $fn
			((rmc++))
		else
			((skc++))
		fi
	done
	((skmonths++))
	((m--))
	if [ $m = 0 ]; then
		m=12
		((y--))
	fi
  done
	echo $skc kept, $rmc removed
fi

exit
