#!/bin/bash

inDir=$1
filExt=m4b

printf '%s\n' "${inDir}" | while IFS= read -r input
do
	# echo "${input}"
	declare -A arr

while IFS='=' read -r key value; do
    arr["$key"]="$value"
done < <(
    ffprobe -v quiet -show_format -print_format json "$input" \
    | jq -r '.format.tags | to_entries[] | "\(.key)=\(.value)"'
)

	trackInfo=${arr[track]}
	curTrk=${trackInfo//\/*}
	maxTrk=${trackInfo//*\/}
	echo l=${#maxTrk}
	read chap < <(printf "%0${#maxTrk}d\n" $curTrk)
	echo $curTrk,$maxTrk
	echo ${arr[title]}
	title=${arr[title]%:*}
	echo ${stitle}
	echo ${title//$curTrk - /}
	echo ${arr[track]}
	echo $chap
	echo ${arr[SERIES]}
	echo ${arr[PART]}
done
