#!/bin/bash

tmpf=$(mktemp mmuttXXXXXX.tmp)

if [ "$2" @= "" ]; then
	pw=$2
fi

if [ ${1:0:1} == / ]; then
	folder=$1
else
	folder="imaps://localhost"
  un=$(echo $1 | cut -d@ -f1)
fi

if [ "$pw" == "" ];then
  cat > $tmpf <<-EOI
	set folder="$folder"
	set imap_user="$un"
  set mime_forward
  set mime_forward_rest=yes
	EOI
else
  cat > $tmpf <<-EOI
	set folder="$folder"
	set imap_user="$un"
	set imap_pass="$pw"
  set mime_forward
  set mime_forward_rest=yes
	EOI
fi
mutt -F $tmpf -f $folder
rm $tmpf
exit
