#!/bin/bash
name="Non-Sequitur"
refurl="http://www.gocomics.com/nonsequitur/"
dst=/home/pi/nonsequitur
fails=$dst/fails.log
nomail=0
precheck=1
maxtries=3
mailto="kardel"
#mailcc="kardel@freenet.de"
#mailcc="Benno.Kardel@web.de,Benno.Kardel@laposte.net"
mailcc=""
mailtohdr=$(echo $mailto | awk '{print $1}')
mailcchdr=$(echo $mailcc | awk '{print $1}')
if [ "$mailcc" != "" ]; then
	recips="$mailto,$mailcc"
else
	recips="$mailto"
fi
fromaddr=nonsequitur@kardel.eu
fromname="${name}-Mailer"
from="\"$fromname\" <$fromaddr>"
sendmail=/usr/sbin/sendmail
stamp=$(date +"%Y-%m-%d")
datepar=$(date +"%Y/%m/%d")
headline="Non Sequitur $(date +%d.%m.%Y)"
once=0
noelderchk=0
chkprevdays=40

myname=$(basename $0)
if [ x$myname = x$0 ]; then
  # Must be in path then
  self=$0
else
  # Get full path to this script, store in $self
  read -d/ begin rest <<<$0
  if [ x$begin = x ]; then # we were invoked fully-qualified
    self=$0
  else
    if [ x$begin = x. ]; then # We were invoked using ./<whatever>
      self=$PWD/$myname
    else
      # We were invoked partially qualified
      self=$PWD/$0
    fi
  fi
fi

function usage() {
  if [ "$1" != 0 ]; then
    outdsc=2
  else
    outdsc=1
  fi
  cat <<EOF >&$outdsc
Usage: $0 <options> [-d YYYY/MM/DD ]
-M            do not send mail
-d            specify a specific date to download
-h            show this help
-o            once a day (no download, if called
              repeatedly and file exists, downloads
              missing preceeding dates also)
-O            same as -o but does not care about
              preceeding dates
-maxtries #   how many tries if download fails 
EOF
  exit $1
}

args=$@ # Remember args for possible recursive calls
tries=1

thisyear=$(date +%Y)

while [ "${1:0:1}" = "-" ]
do
	case "$1" in
		-h|-help|--help)
			usage 0
			exit 0
			;;
		-O)
    	once=1
			;;
		-o)
    	once=1
    	noelderchk=1
			;;
		-M)
    	nomail=1
			;;
		-try)
			shift
			tries=$1
			;;
		-maxtries)
			shift
			maxtries=$1
			;;
		-d)
			shift
			datepar=$1
			stamp=$(echo $1 | awk -F/ '{printf "%04d-%02d-%02d",$1,$2,$3}')
			thisyear=$(echo $1 | awk -F/ '{printf "%04d",$1}')


			headline=$(echo $1 | awk -F/ '{printf "Non Sequitur %02d.%02d.%04d",$3,$2,$1}')
			refurl="${refurl}$1"
  		;;
		*)
    	echo "Unrecognized parameter or option: $1"
    	usage 1
    	exit 1
  		;;
		esac
  shift
done

if [ $once = 1 ] && [ $noelderchk = 0 ]; then
  for ((d = $chkprevdays; d > 0; d--)); do
    urlpostfix=$(date --date=today-${d}days +"%Y/%m/%d")
    $self -O -d $urlpostfix
  done
fi

[ ! -d $dst/$thisyear ] && mkdir $dst/$thisyear
name="${name}-${stamp}"
if [ "$precheck" = 1 ]; then
	if [ -s $dst/$thisyear/$name.* ];then
		exit
	fi
fi
out=$dst/$thisyear/$name.image
[ $once = 1 ] && [ -e $dst/$thisyear/$name.[gpj][inp][fg] ] && exit 0 # Exit if -o and file present

#url=$(wget -O - -q $refurl |awk -F'"' '/<img alt="Non Sequitur" class="strip"/{print $18}')
url=$(wget -O - -q $refurl | awk -Fsrc= '/src="https:\/\/assets.amuniversal.com\//{print $2;exit}' | awk -F'"' '{print $2}')
rm -rf $out.*

wget -q --referer=$refurl -O $out "$url"

if [ -r $out ] && [ "$1" != "-g" ]; then
  filtyp=$(file $out | awk '{print tolower($2)}')
  # Weird but true: The GIF of 2011/03/28 was recognized by file as sun disklbl
  if [ "$filtyp" = "png" ] || [ "$filtyp" = "jpeg" ] || [ "$filtyp" = "gif" ] || [ "$filtyp" = "sun" ]; then
    filext=$(echo $filtyp | sed -e 's/jpeg/jpg/g;s/sun/gif/g')
		if [ $filext = gif ];then
			filext=jpg
    	convert $out $dst/$thisyear/$name.$filext && rm $out
		else
    	mv $out $dst/$thisyear/$name.$filext
		fi
		out=$dst/$thisyear/$name.$filext
		touch -d $stamp $out
    if [ "$nomail" != "1" ]; then
      text=$(
				cat <<EOI
Der aktuelle Non Sequitur Cartoon von Wiley Miller
EOI
      )
      html=$(
        cat <<EOI
<html>
 <body>
  <img alt="" src="cid:imgcid-$stamp">
 </body>
</html>
EOI
      )

      # Construct the HTML part and store it in variable htmlpart
      htmlpart=$(echo "$html" | mime-construct --subpart --type "text/html; charset=utf-8" --encoding base64 --file - --output)
      textpart=$(echo "$text" | mime-construct --subpart --type "text/plain; charset=utf-8" --encoding base64 --file - --output)

			rlist=$(echo $recips|sed -e 's/,/ /g')
			for envto in $rlist
				do
      # Now construct - on the fly - the image part and pipe it into ...
      mime-construct \
        --subpart --type image/$filext \
        --file $out \
        --header "Content-ID: <imgcid-$stamp>" \
        --header "Content-Disposition: inline;" \
        --header " filename=\"Non-Sequitur-$stamp.$filext\"" \
        --output |
        # ... the multipart-command, thus creating the entire message and ...
				(if [ "$mailcc" != "" ]; then \
        mime-construct \
          --header "From: $from" \
          --header "To: $mailtohdr" \
          --header "Cc: $mailcchdr" \
          --subject "$headline" \
          --multipart multipart/related \
          --subpart-string "$textpart" \
          --subpart-file - \
          --subpart-string "$htmlpart" \
          --subpart-file - \
          --output;else \
        mime-construct \
          --header "From: $from" \
          --header "To: $mailtohdr" \
          --header "Cc: $mailcchdr" \
          --subject "$headline" \
          --multipart multipart/related \
          --subpart-string "$textpart" \
          --subpart-file - \
          --subpart-string "$htmlpart" \
          --subpart-file - \
          --output;fi) | \
        # ..finally pipe that into the sendmail command
        $sendmail -f "$from" -r $fromaddr -c $cc $envto
		done
		fi
  else
    if [ "$nomail" != "1" ]; then
    	cat <<EOI | mailx -s "Wiley Miller's Non Sequitur of today failed!" $mailto
Hello, this is $0

I just downloaded $url 
(retrieved using $refurl) into
$out (on $(hostname)).
I expected $out
to be an image, but it turned out to be of type $filtyp.

If you have any idea why, please fix me.

Your sincerely
$0

PS: I deleted $out.

EOI
		else 
			echo >&2 "download try $tries of $maxtries failed: for $datepar"
			if [ $tries -lt $maxtries ]; then
				$self $args -try $((++tries))
			else
				echo $datepar >> $fails
    		rm $out
			fi
		fi
  fi
fi

exit
