- name: MyPlay
  hosts: raspis
  remote_user: pi
  gather_facts: False
  tasks:
  - name: test
    ansible.builtin.command: /bin/date
    register: mydate
  - name: dbg
    debug: 
     msg: "{{mydate.stdout}}"
