#!/bin/bash

# Upload this hosts current
# SSL-cert to Fritzbox

##
# Author: Benno K.
# Email: perlfan@freakmail.de
# Github: https://www.github.com/Benno-K
# 
# This script is available for
# public use under GPL V3 (see
# file LICENSE)
##

# Variables
USERNAME="logfetch"
PASSWORD="fritzbox-password"
CERTPATH="/root/.getssl/fbx.bkpages.de"
CERTPASSWORD=""
HOST=http://fritz.box
KEYFILE=fbx.bkpages.de.key
CHAINFILE=chain.crt
CERTFILE=fbx.bkpages.de.crt
# Login credentials (emcrypted
# password of user above on
# FRITZ!box - saved with
# script fbpwdsave)
credfil="/home/pi/.fblogcred.logfetch"


# make and secure a temporary file
TMP="$(mktemp -t XXXXXX)"
chmod 600 $TMP

# login to the box and get a valid SID
CHALLENGE=`wget -q -O - $HOST/login_sid.lua | sed -e 's/^.*<Challenge>//' -e 's/<\/Challenge>.*$//'`
HASH="`echo -n $CHALLENGE-$(ccat -K "UmVnaXN0cmllcnVuZ3Nwcm96ZXNzODfCpysK" $credfil) | iconv -f ASCII -t UTF16LE |md5sum|awk '{print $1}'`"
SID=`wget -q -O - "$HOST/login_sid.lua?sid=0000000000000000&username=$USERNAME&response=$CHALLENGE-$HASH"| sed -e 's/^.*<SID>//' -e 's/<\/SID>.*$//'`

# generate our upload request
BOUNDARY="---------------------------"`date +%Y%m%d%H%M%S`
printf -- "--$BOUNDARY\r\n" >> $TMP
printf "Content-Disposition: form-data; name=\"sid\"\r\n\r\n$SID\r\n" >> $TMP
printf -- "--$BOUNDARY\r\n" >> $TMP
printf "Content-Disposition: form-data; name=\"BoxCertPassword\"\r\n\r\n$CERTPASSWORD\r\n" >> $TMP
printf -- "--$BOUNDARY\r\n" >> $TMP
printf "Content-Disposition: form-data; name=\"BoxCertImportFile\"; filename=\"BoxCert.pem\"\r\n" >> $TMP
printf "Content-Type: application/octet-stream\r\n\r\n" >> $TMP
cat $CERTPATH/$CERTFILE >> $TMP
cat $CERTPATH/$KEYFILE >> $TMP
cat $CERTPATH/$CHAINFILE >> $TMP
printf "\r\n" >> $TMP
printf -- "--$BOUNDARY--" >> $TMP

exitwith=0
# upload the certificate to the box
wget -q -O - $HOST/cgi-bin/firmwarecfg --header="Content-type: multipart/form-data boundary=$BOUNDARY" --post-file $TMP | grep SSL
if [ $? != 0 ]; then
  echo "Failed to upload certificate to FRITZ!box"
  exitwith=1
fi  

# clean up
rm -f $TMP
exit $exitwith
