#!/bin/bash

set -e

# Function to print usage
usage() {
  cat <<EOF
Usage: $0 [-M] [-d YYYY/MM/DD]
-M  do not send mail
-d  specify a specific date to download
EOF
  exit "$1"
}

# Function to send email
send_email() {
  local text html textpart htmlpart

  text=$(cat <<EOI
Neuer Cartoon von Ralph Ruthe
EOI
  )
  html=$(cat <<EOI
<html>
 <body>
  <img alt="" src="cid:imgcid-$stamp">
 </body>
</html>
EOI
  )

  textpart=$(echo "$text" | mime-construct --subpart --type "text/plain; charset=utf-8" --encoding base64 --file - --output)
  htmlpart=$(echo "$html" | mime-construct --subpart --type "text/html; charset=utf-8" --encoding base64 --file - --output)

  mime-construct \
    --subpart --type image/"$filext" \
    --file "$dst/$filnam" \
    --header "Content-ID: <imgcid-$stamp>" \
    --header "Content-Disposition: inline;" \
    --header " filename=\"Ruthe-$stamp.$filext\"" \
    --output | mime-construct \
    --header "From: $from" \
    --header "To: $mailtohdr" \
    --subject "$headline" \
    --multipart multipart/related \
    --subpart-string "$textpart" \
    --subpart-file - \
    --subpart-string "$htmlpart" \
    --subpart-file - \
    --output | $sendmail -f "$from" -r "$fromaddr" "$mailto"
}

# Fetch current image file
img=$(curl --no-progress-meter https://ruthe.de/ | grep image_src | sed -E 's/.*(https.*strip_[0-9]*.jpg)">/\1/g') || exit $?
[ -z "$img" ] && echo "curl for ruthe failed - try again" >&2 && exit 1
filnam=$(basename "$img")

# Script variables
name="Ruthe"
lcname="ruthe"
refurl="https://ruthe.de/"
dst="/home/pi/$lcname"
nomail=0
mailto="mail@kardel.eu"
mailtohdr=$(echo "$mailto" | awk '{print $1}')
fromaddr="ruthe@kardel.eu"
fromname="${name}-Mailer"
from="\"$fromname\" <$fromaddr>"
sendmail="/usr/sbin/sendmail"
stamp=$(date +"%Y-%m-%d")
headline="Ruthe $(date +%d.%m.%Y)"
once=0
noelderchk=0
chkprevdays=40
myname=$(basename "$0")

# Determine script path
if [ "x$myname" = "x$0" ]; then
  self="$0"
else
  read -d/ begin rest <<<"$0"
  if [ "x$begin" = "x" ]; then
    self="$0"
  elif [ "x$begin" = "x." ]; then
    self="$PWD/$myname"
  else
    self="$PWD/$0"
  fi
fi

# Parse arguments
while [ "$1" != "" ]; do
  case "$1" in
    -h) usage 0 ;;
    -O) noelderchk=1 ;;
    -M) nomail=1 ;;
    -d) shift
        stamp=$(echo "$1" | awk -F/ '{printf "%04d-%02d-%02d",$1,$2,$3}')
        headline=$(echo "$1" | awk -F/ '{printf "Ruthe %02d.%02d.%04d",$3,$2,$1}')
        refurl="${refurl}$1" ;;
    *)  echo "Unrecognized parameter or option: $1"
        usage 1 ;;
  esac
  shift
done

name="${lcname}-${stamp}"
lnk="$dst/$name.image"
out="$dst/$filnam"
wget -q -O "$out" "$img"

if [ -r "$out" ]; then
  filtyp=$(file "$out" | awk '{print tolower($2)}')
  if [[ "$filtyp" =~ ^(png|jpeg|gif|sun)$ ]]; then
    filext=$(echo "$filtyp" | sed -e 's/jpeg/jpg/g;s/sun/gif/g')
    out="$dst/$name.$filext"
    if [ "$nomail" != "1" ]; then
      send_email
    fi
  else
    cat <<EOI | mailx -s "Ralph Ruthe of today failed!" "$mailto"
Hello, this is $0

I just downloaded $url
(retrieved using $refurl) into
$out (on $(hostname)).
I expected $out
to be an image, but it turned out to be of type $filtyp.

If you have any idea why, please fix me.

Your sincerely
$0

PS: I deleted $out.
EOI
    rm "$out"
  fi
fi

exit 0
