#!/bin/bash
##
# Author: HimbeerToni
# Email: Toni.Himbeer@fn.de
# Repos: https://codeberg.org/Himbeertoni/PublicScripts
# 
# This script is available for
# public use under GPL V3 (see
# file LICENSE)
##
#
# $1 ist ham oder spam oder leer
Action="${1:-spam}"
if [ -z "$2" ]; then
	Message="a user classified message as $Action"
else
	Message="user $2 classified message as $Action"
fi
User=", user $2"
if /usr/bin/rspamc learn_$Action; then
    logger -p mail.info -t dovecot-rspamd "$Message"
else
    logger -p mail.err -t dovecot-rspamd "FAIL: learning $Action"
fi
