#!/bin/bash
# $1 ist ham oder spam oder leer
Action="${1:-spam}"

if /usr/bin/rspamc learn_$Action; then
    logger -p mail.info -t dovecot-rspamd "learned $Action"
else
    logger -p mail.err -t dovecot-rspamd "FAIL: learning $Action"
fi
