#!/bin/bash
xup () {
	upper=$(dirname "$1")
	while [ "$upper" != "/" ]
	do
		setfacl -m u:debian-spamd:x $upper
		upper=$(dirname "$upper")
	done
}
if [ ${#@} = 0 ]; then
	find -L /home /data /ssd -maxdepth 8 -name .Junk -exec $0 '{}/cur/' \;
	exit 0
else
	xup "$1"
	[ $(ls -1 "$1/" | wc -l) = 0 ] && exit 0 || echo learning "$1";setfacl -R -m user:debian-spamd:rwx "$1";sudo -u debian-spamd sa-learn --spam "$1";exit 0
fi
exit 4 # should never be reached
