#!/bin/bash

doupd () {
	echo n|apt-get upgrade|grep -q syncthing
	if [ $? = 0 ]; then 
		export LC_ALL=C
		export DEBIAN_FRONTEND=noninteractive
		apt-get -y install \
			  -o Dpkg::Options::="--force-confdef" \
				-o Dpkg::Options::="--force-confold" \
        -o Dpkg::Progress-Fancy="0" \
        -o Dpkg::Use-Pty="0" \
				syncthing
	fi
}

if [ $UID = 0 ]; then
	doupd
else
	sudo $0
fi
