#!/bin/bash

doupd () {
	echo n|apt-get upgrade|grep -q syncthing
	if [ $? = 0 ]; then 
		export LC_ALL=C
		export DEBIAN_FRONTEND=noninteractive
				apt-get -y install syncthing
	fi
}

if [ $UID = 0 ]; then
	doupd
else
	sudo $0
fi
