#!/bin/bash
smartphone=s24
dest=/data/backups/termux
target=home.$(($(date -d "today 00:00" +%s)/86400%3+1)).tgz
prkey=/home/pi/.ssh/termuxbck
sshopts="-o BatchMode=yes -o IdentitiesOnly=yes -i $prkey -o PasswordAuthentication=no -o KbdInteractiveAuthentication=no"
ssh $sshopts smartphone tar --warning=no-file-ignored -czf - ${1-.} | dd status=none of=$dest/$target
