#!/bin/bash
# Recipient?
if [ "$1" != "" ]; then
  mailto="$1"
else
  read -p "To: " mailto
fi

cntfil=~/.testmailcnt
if [ -r $cntfil ]; then
  cnt=$(cat ~/.testmailcnt)
else
	cnt=0
fi
((cnt++))
echo -n $cnt > $cntfil

# Send mail
date +"Sent at $(date +%T)"|mail -s "Testmail $cnt" $mailto
echo "Testmail $cnt"
exit
