#!/bin/bash
# Recipient?
if [ "$1" != "" ]; then
  mailto="$1"
else
  read -p "To: " mailto
fi

cntfil=~/.testmailcnt
logfil=~/testmail.log
if [ -r $cntfil ]; then
  cnt=$(cat ~/.testmailcnt)
else
	cnt=0
fi
((cnt++))
echo -n $cnt > $cntfil

# Send mail
echo "Sent by $USER at $(date +%T) on $(hostname) to $mailto"|mail -s "Testmail $cnt by $USER" $mailto
echo "Testmail $cnt by $USER"
# Log
date "+$cnt %F %T $mailto" >> $logfil
exit
