#!/bin/bash
# check for any apt-packages that need update, if
# there are ones send a mail

# mail recipient and program
mailto=${1:root}
mailer=${2:mutt}

# our name
bn=$(basename $0)

# create a temporary file and make sure to clean it up
tmpf=$(mktemp /tmp/$bn-XXXXXXXY.tmp)
trap "rm -rf $tmpf" SIGINT SIGSTOP EXIT

# list upgradadeable packages and determine the count
(( cntupg=$(apt list --upgradeable 2>/dev/null|tee -a $tmpf|wc -l)-1 ))

# test-mode: assume there are packages to upgrade,
# you may specify the number of packages after -t,
# if you don't we will make it 99999
if [ "$1" = "-t" ]; then
  cntupg=${2:-99999}
	faked="faked "
fi 

# send mail about upgraded packages, if there are ones
if [ $cntupg -gt 0 ]; then
	 $mailer -s "$bn: There are $cntupg ${faked}packages to upgrade" "$mailto"  < $tmpf
fi
exit # Removes $tmpf due to trap!
