#!/bin/bash

# Start whatever program
# and mail it's output
# if there is output.
# The program to be started
# is taken from the name 
# of (the soft-link of)
# this script.
# So to run a script named
# "hugo" create a soft-link
# named "hugorun" pointing
# to this script

function format4html(){
  cat<<EOI
<html>
<body>
<pre>
<code>
$(cat)
</code>
</pre>
</body>
</html>
EOI
  return
}
if [ x$1 == x ]; then
	read -p "Mail address: " mailto
else
	mailto=$1
	shift
fi
if [ "$1" == "" ]; then
	read -p "Subject: " subj
else
	subj=$@
fi

export LANGUAGE="C"
dusage="echo -n"
myname=$(basename $0)
progname=${myname:0:-3}
here=$(dirname $0)
mailcontent=$($here/$progname)
if [ ${#mailcontent} -ne  0 ]; then
	echo "$mailcontent"|format4html|mail -a 'Content-type: text/html' -s "$subj" $mailto
fi
exit
